version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: geoip_sqlserver
    environment:
      MSSQL_SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_MEMORY_LIMIT_MB: "2048"
      MSSQL_OPTION_FLAGS: "-C"
    ports:
      - "1433:1433"
    security_opt:
      - seccomp=unconfined
    volumes:
      - sql_data:/var/opt/mssql
      - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - geoip-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Password123" -d master -C -Q "SELECT 1" -b -o /dev/null
      timeout: 10s
      retries: 15
      interval: 10s
      start_period: 60s  

  redis:
    image: redis:latest
    container_name: geoip_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    networks:
      - geoip-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 10s
      interval: 5s
      retries: 5
      start_period: 20s
  

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geoip_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=GeoIPDb;User=sa;Password=YourStrong@Password123;TrustServerCertificate=true;Connect Timeout=30
      - ConnectionStrings__Redis=geoip_redis:6379,abortConnect=false,connectRetry=5,connectTimeout=5000,syncTimeout=5000
      - Quartz__jobStore__type=Quartz.Simpl.RAMJobStore, Quartz
      - Quartz__threadPool__type=Quartz.Simpl.SimpleThreadPool, Quartz
      - Quartz__threadPool__threadCount=5
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - geoip-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      timeout: 10s
      retries: 5
      start_period: 30s


volumes:
  sql_data:
  redis_data:

networks:
  geoip-network:
    driver: bridge
